//! NORMATIVE FORMAT — Schema Snapshot (`schema.rs`), storage boundary B2.
//!
//! This file shows the exact shape the CLI emits (ADR-001). It is MACHINE-OWNED
//! in consumer repos: overwrite-always, never hand-edited, always committed.
//! Both introspection frontends (postgres | openapi) emit this identical shape.
//!
//! Format evolution: the marker below is checked by the derivation macros;
//! an incompatible marker fails the build with "re-run `gpui-admin introspect`"
//! (Compatibility Policy §4).

// ============================================================
// GENERATED BY gpui-admin — DO NOT EDIT
// gpui-admin snapshot format: 1
// source: postgres (schema "public")   [or: openapi <title> <version>]
// ============================================================

/// One module per captured Resource.
pub mod user {
    /// The Record shape. Field order = Snapshot canonical order.
    #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
    pub struct User {
        pub id: uuid::Uuid,                       // primary key
        pub org_id: uuid::Uuid,                   // FK → organization (relation table below)
        pub name: String,                         // NOT NULL
        pub email: String,                        // NOT NULL, UNIQUE
        pub status: UserStatus,                   // enum type, NOT NULL
        pub last_seen_at: Option<time::OffsetDateTime>, // nullable
        pub created_at: time::OffsetDateTime,     // server-owned (default now())
    }

    /// Enum types captured from the source (DB enum / OpenAPI string enum).
    #[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    pub enum UserStatus { Active, Suspended, Invited }

    /// Typed field identity — the universal key (filters, sort, projections,
    /// dirty bitsets, invalidation, validation routing).
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub enum UserField { Id, OrgId, Name, Email, Status, LastSeenAt, CreatedAt }

    /// Per-Field metadata table consumed by derivation and the Scaffolder.
    /// (Representative entries; one row per Field.)
    pub const FIELDS: &[FieldMeta] = &[
        FieldMeta { field: UserField::Id,        name: "id",         nullable: false, server_owned: true,  unique: true  },
        FieldMeta { field: UserField::OrgId,     name: "org_id",     nullable: false, server_owned: false, unique: false },
        FieldMeta { field: UserField::Email,     name: "email",      nullable: false, server_owned: false, unique: true  },
        FieldMeta { field: UserField::CreatedAt, name: "created_at", nullable: false, server_owned: true,  unique: false },
        // ...
    ];

    /// FK relations captured from constraints (postgres) or reference
    /// annotations (openapi). Targets are TYPE references — boot-asserted.
    pub const RELATIONS: &[RelationMeta] = &[
        RelationMeta { via: UserField::OrgId, target_key: "organizations" },
    ];

    pub struct FieldMeta {
        pub field: UserField,
        pub name: &'static str,
        pub nullable: bool,
        /// Server-owned Fields are excluded from CreatePayload generation.
        pub server_owned: bool,
        pub unique: bool,
    }
    pub struct RelationMeta { pub via: UserField, pub target_key: &'static str }
}

// pub mod organization { ... same shape ... }
// pub mod ticket { ... same shape ... }
