//! NORMATIVE FORMAT — Schema Snapshot (`schema.rs`), storage boundary B2.
//!
//! This file shows the exact shape the CLI emits (ADR-001). It is MACHINE-OWNED
//! in consumer repos: overwrite-always, never hand-edited, always committed.
//! Both introspection frontends (postgres | openapi) emit this identical shape.
//!
//! Format evolution: the marker below is checked by the derivation macros;
//! an incompatible marker fails the build with "re-run `gpui-admin introspect`"
//! (Compatibility Policy §4).

// ============================================================
// GENERATED BY gpui-admin — DO NOT EDIT
// gpui-admin snapshot format: 2
// source: postgres (schema "public")   [or: openapi <title> <version>]
// binding: <provider-key | "default">
// ============================================================

/// One module per captured Resource.
pub mod user {
    /// The Record shape. Field order = Snapshot canonical order.
    #[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
    pub struct User {
        pub id: uuid::Uuid,                       // primary key
        pub org_id: uuid::Uuid,                   // FK → organization (relation table below)
        pub name: String,                         // NOT NULL
        pub email: String,                        // NOT NULL, UNIQUE
        pub status: UserStatus,                   // enum type, NOT NULL
        pub last_seen_at: Option<time::OffsetDateTime>, // nullable; kind: TimestampAware
        pub balance: Option<Decimal>,             // nullable; kind: Decimal (exact)
        pub created_at: time::OffsetDateTime,     // server-owned; kind: TimestampAware
    }

    /// Enum types captured from the source (DB enum / OpenAPI string enum).
    #[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
    #[serde(rename_all = "snake_case")]
    pub enum UserStatus { Active, Suspended, Invited }

    /// Typed field identity — the universal key (filters, sort, projections,
    /// dirty bitsets, invalidation, validation routing).
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
    pub enum UserField { Id, OrgId, Name, Email, Status, LastSeenAt, Balance, CreatedAt }

    /// Per-Field metadata table consumed by derivation and the Scaffolder.
    /// (Representative entries; one row per Field.) `kind` drives type-faithful
    /// rendering (CAP-211) and exact-decimal handling (CAP-312); naive temporal
    /// kinds render verbatim, aware instants convert only at display.
    pub const FIELDS: &[FieldMeta] = &[
        FieldMeta { field: UserField::Id,        name: "id",          nullable: false, server_owned: true,  unique: true,  kind: FieldKind::Uuid },
        FieldMeta { field: UserField::OrgId,     name: "org_id",      nullable: false, server_owned: false, unique: false, kind: FieldKind::Uuid },
        FieldMeta { field: UserField::Email,     name: "email",       nullable: false, server_owned: false, unique: true,  kind: FieldKind::Text },
        FieldMeta { field: UserField::LastSeenAt,name: "last_seen_at",nullable: true,  server_owned: false, unique: false, kind: FieldKind::TimestampAware },
        FieldMeta { field: UserField::Balance,   name: "balance",     nullable: true,  server_owned: false, unique: false, kind: FieldKind::Decimal },
        FieldMeta { field: UserField::CreatedAt, name: "created_at",  nullable: false, server_owned: true,  unique: false, kind: FieldKind::TimestampAware },
        // ...
    ];

    /// FK relations captured from constraints (postgres) or reference
    /// annotations (openapi). Targets are TYPE references — boot-asserted.
    /// `self_ref` marks self-referencing relations (hierarchy cues, CAP-212).
    pub const RELATIONS: &[RelationMeta] = &[
        RelationMeta { via: UserField::OrgId, target_key: "organizations", self_ref: false },
    ];

    /// Junction candidates: tables whose Snapshot shows exactly two FK relations
    /// (Q25 ruling). Detection is advisory — the Adopter decides at declaration
    /// time whether a candidate is a pure junction or an ordinary Resource.
    pub const JUNCTIONS: &[JunctionMeta] = &[
        // JunctionMeta { key: "user_roles", side_a: ("users", "user_id"), side_b: ("roles", "role_id") },
    ];

    pub struct FieldMeta {
        pub field: UserField,
        pub name: &'static str,
        pub nullable: bool,
        /// Server-owned Fields are excluded from CreatePayload generation.
        pub server_owned: bool,
        pub unique: bool,
        /// Type-faithful scalar kind (format 2): Bool, I32, I64, F64, Decimal,
        /// Text, Date, Time, TimestampNaive, TimestampAware, Uuid, Enum, Json.
        pub kind: FieldKind,
    }
    pub struct RelationMeta { pub via: UserField, pub target_key: &'static str, pub self_ref: bool }
    pub struct JunctionMeta { pub key: &'static str, pub side_a: (&'static str, &'static str), pub side_b: (&'static str, &'static str) }
}

// pub mod organization { ... same shape ... }
// pub mod ticket { ... same shape ... }
